version: 2

project_name: iampg

builds:
  - main: .
    binary: iampg
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/LeRedTeam/iampg/cmd.version={{.Version}}
      - -X github.com/LeRedTeam/iampg/license.publicKeyBase64={{ .Env.IAMPG_PUBLIC_KEY }}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: LeRedTeam
    name: iampg
  draft: false
  prerelease: auto
